#finetune config

version: '50.0'
#bert_config: 'configs/config_bert.json'

# model
distrill: False
max_frames: 14
frame_embedding_size: 1024

temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4
cross_layers_num: 3

# train
train_batch_size: 16
val_batch_size: 64
test_batch_size: 128
max_epochs: 10
print_steps: 100
warmup_ratio: 0.1
lr: 5e-5
other_lr: 1e-4
weight_decay: 0.000001
adam_epsilon: 0.000001
max_grad_norm: 5
accum_step: 2

other_lr_layers: ["linear", "cross_layers"]

# file
resume: ''
pretrain_file: '../models/pretrain/5.0/pretrain_model_epoch_10.bin'

