# pretrain config

version: '7.0'
# bert_config: 'configs/config_bert.json'

# model
embed_dim: 256 # 动量嵌入低维
max_frames: 8
frame_embedding_size: 1024

temp: 0.07
mlm_probability: 0.15
queue_size: 65568
momentum: 0.995
alpha: 0.4
cross_layers_num: 3

# train
train_batch_size: 128
max_epochs: 10
print_steps: 100
warmup_ratio: 0.03
lr: 1e-4
other_lr: 5e-4
weight_decay: 0.01
adam_epsilon: 0.000001
max_grad_norm: 1
accum_step: 1

other_lr_layers: ["itm_head", "mlm_head", "cross_layers", "video_proj", "text_proj", "video_proj_linear"]



